version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  lint_code:
    executor: node/default
    description: Lint code
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Lint code
          command: npm run lint:fix
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - package-lock.json
            - package.json
            - src
            - .eslintrc.js
            - .prettierrc.js
            - .gitignore
            - .npmignore
            - .nvmrc
            - .circleci
            - rollup.config.mjs
            - commitlint.config.js
            - tsconfig.json
            - .husky

workflows:
  build_app:
    jobs:
      - lint_code
